name: flutter_math
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.2.0 


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images.png
   - assets/mey.jpg
# Math
# Images Lesson1
   - lib/math/Assets/Imageslesson1/image1.jpg
   - lib/math/Assets/Imageslesson1/image2.jpg
   - lib/math/Assets/Imageslesson1/image3.jpg
   - lib/math/Assets/Imageslesson1/image4.jpg
   - lib/math/Assets/Imageslesson1/image5.jpg
   - lib/math/Assets/Imageslesson1/image6.jpg
# Images Lesson2
   - lib/math/Assets/Imageslesson2/image1.jpg
   - lib/math/Assets/Imageslesson2/image2.jpg
   - lib/math/Assets/Imageslesson2/image3.jpg
   - lib/math/Assets/Imageslesson2/image4.jpg
# Images Lesson3
   - lib/math/Assets/Imageslesson3/image1.jpg
   - lib/math/Assets/Imageslesson3/image2.jpg
   - lib/math/Assets/Imageslesson3/image3.jpg 
# Images Lesson4
   - lib/math/Assets/Imageslesson4/image1.jpg
   - lib/math/Assets/Imageslesson4/image2.jpg
   - lib/math/Assets/Imageslesson4/image3.jpg 
# Images Lesson5
   - lib/math/Assets/Imageslesson5/image1.jpg
   - lib/math/Assets/Imageslesson5/image2.jpg
   - lib/math/Assets/Imageslesson5/image3.jpg 
# Images Lesson6
   - lib/math/Assets/Imageslesson6/image1.jpg
   - lib/math/Assets/Imageslesson6/image2.jpg
   - lib/math/Assets/Imageslesson6/image3.jpg 
# Images Lesson7
   - lib/math/Assets/Imageslesson7/image1.jpg
   - lib/math/Assets/Imageslesson7/image2.jpg
   - lib/math/Assets/Imageslesson7/image3.jpg 
   - lib/math/Assets/Imageslesson7/image4.jpg
   - lib/math/Assets/Imageslesson7/image5.jpg
# Images Lesson8
   - lib/math/Assets/Imageslesson8/image.jpg
# Images Lesson9
   - lib/math/Assets/Imageslesson9/image.jpg
# Images Lesson10
   - lib/math/Assets/Imageslesson10/image1.jpg
   - lib/math/Assets/Imageslesson10/image2.jpg
   - lib/math/Assets/Imageslesson10/image3.jpg 
   - lib/math/Assets/Imageslesson10/image4.jpg
# Images Lesson11
   - lib/math/Assets/Imageslesson11/image1.jpg
   - lib/math/Assets/Imageslesson11/image2.jpg
   - lib/math/Assets/Imageslesson11/image3.jpg 
   - lib/math/Assets/Imageslesson11/image4.jpg
# Physics
# Images Lesson1
   - lib/physics/Assets/Imageslesson1/image1.jpg
   - lib/physics/Assets/Imageslesson1/image2.jpg
# Images Lesson2
   - lib/physics/Assets/Imageslesson2/image1.jpg
   - lib/physics/Assets/Imageslesson2/image2.jpg
# Images Lesson3
   - lib/physics/Assets/Imageslesson3/image1.jpg
# Images Lesson4
   - lib/physics/Assets/Imageslesson4/image1.jpg
   - lib/physics/Assets/Imageslesson4/image2.jpg
# Images Lesson5
   - lib/physics/Assets/Imageslesson5/image1.jpg
   - lib/physics/Assets/Imageslesson5/image2.jpg
# Images Lesson6
   - lib/physics/Assets/Imageslesson6/image1.jpg
   - lib/physics/Assets/Imageslesson6/image2.jpg
# Images Lesson7
   - lib/physics/Assets/Imageslesson7/image1.jpg
   - lib/physics/Assets/Imageslesson7/image2.jpg
# Images Lesson8
   - lib/physics/Assets/Imageslesson8/image1.jpg
   - lib/physics/Assets/Imageslesson8/image2.jpg
   - lib/physics/Assets/Imageslesson8/image3.jpg
# Images Lesson9
   - lib/physics/Assets/Imageslesson9/image1.jpg
   - lib/physics/Assets/Imageslesson9/image2.jpg
   - lib/physics/Assets/Imageslesson9/image3.jpg
   - lib/physics/Assets/Imageslesson9/image4.jpg
   - lib/physics/Assets/Imageslesson9/image5.jpg
   - lib/physics/Assets/Imageslesson9/image6.jpg
   - lib/physics/Assets/Imageslesson9/image7.jpg
# Chemistry
# Images lesson
   - lib/chemistry/Assets/Imageslesson1/image1.jpg
   - lib/chemistry/Assets/Imageslesson1/image2.jpg
   - lib/chemistry/Assets/Imageslesson1/image3.jpg
   - lib/chemistry/Assets/Imageslesson1/image4.jpg
   - lib/chemistry/Assets/Imageslesson1/image5.jpg
   - lib/chemistry/Assets/Imageslesson1/image6.jpg
   - lib/chemistry/Assets/Imageslesson1/image7.jpg
   - lib/chemistry/Assets/Imageslesson1/image8.jpg
   - lib/chemistry/Assets/Imageslesson1/image9.jpg
   - lib/chemistry/Assets/Imageslesson1/image10.jpg
   - lib/chemistry/Assets/Imageslesson1/image11.jpg
   - lib/chemistry/Assets/Imageslesson1/image12.jpg
   - lib/chemistry/Assets/Imageslesson1/image13.jpg
   - lib/chemistry/Assets/Imageslesson1/image14.jpg
   - lib/chemistry/Assets/Imageslesson1/image15.jpg
   - lib/chemistry/Assets/Imageslesson1/image16.jpg
   - lib/chemistry/Assets/Imageslesson1/image17.jpg
   - lib/chemistry/Assets/Imageslesson1/image18.jpg
   - lib/chemistry/Assets/Imageslesson1/image19.jpg
   - lib/chemistry/Assets/Imageslesson1/image20.jpg
   - lib/chemistry/Assets/Imageslesson1/image21.jpg
   - lib/chemistry/Assets/Imageslesson1/image22.jpg
   - lib/chemistry/Assets/Imageslesson1/image23.jpg
   - lib/chemistry/Assets/Imageslesson1/image24.jpg
   - lib/chemistry/Assets/Imageslesson1/image25.jpg
   - lib/chemistry/Assets/Imageslesson1/image26.jpg
   - lib/chemistry/Assets/Imageslesson1/image27.jpg
# Biology
# Images lesson
   - lib/biology/Assets/Imageslesson1/image1.jpg
   - lib/biology/Assets/Imageslesson1/image2.jpg
   - lib/biology/Assets/Imageslesson1/image3.jpg
   - lib/biology/Assets/Imageslesson1/image4.jpg
   - lib/biology/Assets/Imageslesson1/image5.jpg
   - lib/biology/Assets/Imageslesson1/image6.jpg
   - lib/biology/Assets/Imageslesson1/image7.jpg
   - lib/biology/Assets/Imageslesson1/image8.jpg
   - lib/biology/Assets/Imageslesson1/image9.jpg
   - lib/biology/Assets/Imageslesson1/image10.jpg
   - lib/biology/Assets/Imageslesson1/image11.jpg
   - lib/biology/Assets/Imageslesson1/image12.jpg
   - lib/biology/Assets/Imageslesson1/image13.jpg
   - lib/biology/Assets/Imageslesson1/image14.jpg
   - lib/biology/Assets/Imageslesson1/image15.jpg
   - lib/biology/Assets/Imageslesson1/image16.jpg
   - lib/biology/Assets/Imageslesson1/image17.jpg
   - lib/biology/Assets/Imageslesson1/image18.jpg
   - lib/biology/Assets/Imageslesson1/image19.jpg
   - lib/biology/Assets/Imageslesson1/image20.jpg

   



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
