import 'package:flutter/material.dart';
class chemistry extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("រូបមន្តគីមីវិទ្យា"),
      ),
      body: ListView(
        scrollDirection: Axis.vertical,
        children: <Widget>[
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image1.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image2.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image3.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image4.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image5.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image6.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image7.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image8.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image9.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image10.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image11.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image12.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image13.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image14.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image15.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image16.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image17.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image18.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image19.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image20.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image21.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image22.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image23.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image24.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image25.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image26.jpg'),
          fit: BoxFit.cover,
          ),
          Image(image: AssetImage('lib/chemistry/Assets/Imageslesson1/image27.jpg'),
          fit: BoxFit.cover,
          ),
        ],
      ),
    );
  }
}